import test from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import worker,{passwordHash,digest} from '../cloudflare-family/worker.mjs';
class D1 {
 constructor(schema){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL(schema,import.meta.url),'utf8'))}
 prepare(sql){const db=this.db;let params=[];return {bind(...p){params=p;return this},async first(){return db.prepare(sql).get(...params)||null},async all(){return {results:db.prepare(sql).all(...params)}},async run(){const r=db.prepare(sql).run(...params);return {meta:{changes:Number(r.changes)}}}}}
 async batch(statements){this.db.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());this.db.exec('COMMIT');return result}catch(e){this.db.exec('ROLLBACK');throw e}}
}
const base={firstName:'تجريبي',fatherName:'نموذج',grandName:'',branch:'فرع',gender:'unknown',birthYear:'1960',deathYear:'',life:'alive',marital:'unknown',parentId:'',city:'',profession:'',education:'',phone:'PRIVATE_PHONE',email:'private@example.test',notes:'PRIVATE_NOTES',duesPaid:'PRIVATE_DUES',version:1,archived:0};
async function setup(role='admin',regions=['quds','jordan']){
 const env={ALLOWED_ORIGIN:'https://gazynn-sketch.github.io',AUTH_DB:new D1('../cloudflare-family/schema-auth.sql'),QUDS_DB:new D1('../cloudflare-family/schema-region.sql'),JORDAN_DB:new D1('../cloudflare-family/schema-region.sql')};
 for(const r of ['quds','jordan']){const data={people:[{...base,id:r+'-1',region:r}],branches:['فرع'],audit:[],users:[]};await env[r==='quds'?'QUDS_DB':'JORDAN_DB'].prepare('INSERT INTO registry(id,revision,data) VALUES(1,1,?)').bind(JSON.stringify(data)).run()}
 const hash=await passwordHash('test-password-123','salt');await env.AUTH_DB.prepare('INSERT INTO users(id,username,name,role,regions,password_hash,salt) VALUES(?,?,?,?,?,?,?)').bind('u1','tester','Test',role,JSON.stringify(regions),hash,'salt').run();
 const call=async(path,body,token,method=body?'POST':'GET',origin=env.ALLOWED_ORIGIN)=>worker.fetch(new Request('https://example.test/api/'+path,{method,headers:{Origin:origin,'CF-Connecting-IP':'192.0.2.1',...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);
 const login=await call('login',{username:'tester',password:'test-password-123'});assert.equal(login.status,200);const {token}=await login.json();return {env,call,token};
}
test('login protects data; viewer scope and field redaction enforced by server',async()=>{const {call,token}=await setup('viewer',['jordan']);assert.equal((await call('data?region=jordan')).status,401);assert.equal((await call('data?region=quds',undefined,token)).status,403);const response=await call('data?region=jordan',undefined,token);assert.match(response.headers.get('Cache-Control'),/no-store/);const d=await response.json();assert.equal(d.people.length,1);for(const k of ['phone','email','notes','duesPaid'])assert.equal(d.people[0][k],undefined);assert.equal((await call('members?region=jordan',base,token)).status,403)});
test('editor save persists, cross-region parent rejected, stale edit rejected',async()=>{const {call,token}=await setup('editor');let r=await call('members/quds-1?region=quds',{...base,parentId:'jordan-1'},token,'PUT');assert.equal(r.status,400);r=await call('members/quds-1?region=quds',{...base,firstName:'محدث'},token,'PUT');assert.equal(r.status,200);assert.equal((await call('members/quds-1?region=quds',base,token,'PUT')).status,409);const d=await(await call('data?region=quds',undefined,token)).json();assert.equal(d.people[0].firstName,'محدث');assert.equal(d.people[0].version,2);const j=await(await call('data?region=jordan',undefined,token)).json();assert.equal(j.people[0].firstName,base.firstName)});
test('logout and disabled users immediately revoke sessions',async()=>{const {env,call,token}=await setup();assert.equal((await call('logout?region=quds',{},token)).status,200);assert.equal((await call('data?region=quds',undefined,token)).status,401);const fresh=await(await call('login',{username:'tester',password:'test-password-123'})).json();await env.AUTH_DB.prepare('UPDATE users SET enabled=0 WHERE id=?').bind('u1').run();assert.equal((await call('data?region=quds',undefined,fresh.token)).status,401)});
test('wrong origin rejected and repeated failed logins rate limited',async()=>{const {call,token}=await setup();assert.equal((await call('data?region=quds',undefined,token,'GET','https://evil.example')).status,403);for(let i=0;i<9;i++)assert.equal((await call('login',{username:'tester',password:'wrong'})).status,401);assert.equal((await call('login',{username:'tester',password:'wrong'})).status,429)});
test('user creation cannot widen administrator region scope',async()=>{const {call,token}=await setup('admin',['quds']);assert.equal((await call('users?region=quds',{name:'new',username:'new',role:'admin',regions:['jordan'],password:'test-password-456'},token)).status,403)});
